// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal_message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_internal_5fmessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_internal_5fmessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
#include "chat_content.pb.h"
#include "history.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_internal_5fmessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_internal_5fmessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[9]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_internal_5fmessage_2eproto;
namespace msg {
class Chat;
class ChatDefaultTypeInternal;
extern ChatDefaultTypeInternal _Chat_default_instance_;
class FriendNotification;
class FriendNotificationDefaultTypeInternal;
extern FriendNotificationDefaultTypeInternal _FriendNotification_default_instance_;
class GroupNotification;
class GroupNotificationDefaultTypeInternal;
extern GroupNotificationDefaultTypeInternal _GroupNotification_default_instance_;
class MoneyNotification;
class MoneyNotificationDefaultTypeInternal;
extern MoneyNotificationDefaultTypeInternal _MoneyNotification_default_instance_;
class Notification;
class NotificationDefaultTypeInternal;
extern NotificationDefaultTypeInternal _Notification_default_instance_;
class Seen;
class SeenDefaultTypeInternal;
extern SeenDefaultTypeInternal _Seen_default_instance_;
class Status;
class StatusDefaultTypeInternal;
extern StatusDefaultTypeInternal _Status_default_instance_;
class TextNotification;
class TextNotificationDefaultTypeInternal;
extern TextNotificationDefaultTypeInternal _TextNotification_default_instance_;
class Typing;
class TypingDefaultTypeInternal;
extern TypingDefaultTypeInternal _Typing_default_instance_;
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> ::msg::Chat* Arena::CreateMaybeMessage<::msg::Chat>(Arena*);
template<> ::msg::FriendNotification* Arena::CreateMaybeMessage<::msg::FriendNotification>(Arena*);
template<> ::msg::GroupNotification* Arena::CreateMaybeMessage<::msg::GroupNotification>(Arena*);
template<> ::msg::MoneyNotification* Arena::CreateMaybeMessage<::msg::MoneyNotification>(Arena*);
template<> ::msg::Notification* Arena::CreateMaybeMessage<::msg::Notification>(Arena*);
template<> ::msg::Seen* Arena::CreateMaybeMessage<::msg::Seen>(Arena*);
template<> ::msg::Status* Arena::CreateMaybeMessage<::msg::Status>(Arena*);
template<> ::msg::TextNotification* Arena::CreateMaybeMessage<::msg::TextNotification>(Arena*);
template<> ::msg::Typing* Arena::CreateMaybeMessage<::msg::Typing>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace msg {

enum Status_Type : int {
  Status_Type_UNKNOWN = 0,
  Status_Type_ONLINE = 1,
  Status_Type_OFFLINE = 2,
  Status_Type_BUSY = 3,
  Status_Type_NO_BOTHER = 4,
  Status_Type_Status_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Status_Type_Status_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Status_Type_IsValid(int value);
constexpr Status_Type Status_Type_Type_MIN = Status_Type_UNKNOWN;
constexpr Status_Type Status_Type_Type_MAX = Status_Type_NO_BOTHER;
constexpr int Status_Type_Type_ARRAYSIZE = Status_Type_Type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Status_Type_descriptor();
template<typename T>
inline const std::string& Status_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Status_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Status_Type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Status_Type_descriptor(), enum_t_value);
}
inline bool Status_Type_Parse(
    const std::string& name, Status_Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Status_Type>(
    Status_Type_descriptor(), name, value);
}
enum FriendNotification_Status : int {
  FriendNotification_Status_UNKNOWN = 0,
  FriendNotification_Status_SENT = 1,
  FriendNotification_Status_ACCEPT = 2,
  FriendNotification_Status_DECLINE = 3,
  FriendNotification_Status_BLOCK = 4,
  FriendNotification_Status_FriendNotification_Status_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  FriendNotification_Status_FriendNotification_Status_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool FriendNotification_Status_IsValid(int value);
constexpr FriendNotification_Status FriendNotification_Status_Status_MIN = FriendNotification_Status_UNKNOWN;
constexpr FriendNotification_Status FriendNotification_Status_Status_MAX = FriendNotification_Status_BLOCK;
constexpr int FriendNotification_Status_Status_ARRAYSIZE = FriendNotification_Status_Status_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* FriendNotification_Status_descriptor();
template<typename T>
inline const std::string& FriendNotification_Status_Name(T enum_t_value) {
  static_assert(::std::is_same<T, FriendNotification_Status>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function FriendNotification_Status_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    FriendNotification_Status_descriptor(), enum_t_value);
}
inline bool FriendNotification_Status_Parse(
    const std::string& name, FriendNotification_Status* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<FriendNotification_Status>(
    FriendNotification_Status_descriptor(), name, value);
}
// ===================================================================

class Chat PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.Chat) */ {
 public:
  inline Chat() : Chat(nullptr) {};
  virtual ~Chat();

  Chat(const Chat& from);
  Chat(Chat&& from) noexcept
    : Chat() {
    *this = ::std::move(from);
  }

  inline Chat& operator=(const Chat& from) {
    CopyFrom(from);
    return *this;
  }
  inline Chat& operator=(Chat&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Chat& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Chat* internal_default_instance() {
    return reinterpret_cast<const Chat*>(
               &_Chat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Chat& a, Chat& b) {
    a.Swap(&b);
  }
  inline void Swap(Chat* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Chat* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Chat* New() const final {
    return CreateMaybeMessage<Chat>(nullptr);
  }

  Chat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Chat>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Chat& from);
  void MergeFrom(const Chat& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Chat* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.Chat";
  }
  protected:
  explicit Chat(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_internal_5fmessage_2eproto);
    return ::descriptor_table_internal_5fmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 4,
    kTimestampFieldNumber = 5,
    kUserIdFieldNumber = 1,
    kChannelIdFieldNumber = 2,
    kMessageIdFieldNumber = 3,
  };
  // .msg.ChatContent content = 4;
  bool has_content() const;
  private:
  bool _internal_has_content() const;
  public:
  void clear_content();
  const ::msg::ChatContent& content() const;
  ::msg::ChatContent* release_content();
  ::msg::ChatContent* mutable_content();
  void set_allocated_content(::msg::ChatContent* content);
  private:
  const ::msg::ChatContent& _internal_content() const;
  ::msg::ChatContent* _internal_mutable_content();
  public:
  void unsafe_arena_set_allocated_content(
      ::msg::ChatContent* content);
  ::msg::ChatContent* unsafe_arena_release_content();

  // .google.protobuf.Timestamp timestamp = 5;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // uint64 user_id = 1 [jstype = JS_STRING];
  void clear_user_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 user_id() const;
  void set_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_user_id() const;
  void _internal_set_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 channel_id = 2 [jstype = JS_STRING];
  void clear_channel_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 channel_id() const;
  void set_channel_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_channel_id() const;
  void _internal_set_channel_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 message_id = 3 [jstype = JS_STRING];
  void clear_message_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 message_id() const;
  void set_message_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_message_id() const;
  void _internal_set_message_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:msg.Chat)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::msg::ChatContent* content_;
  PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint64 user_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 channel_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 message_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_internal_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class Seen PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.Seen) */ {
 public:
  inline Seen() : Seen(nullptr) {};
  virtual ~Seen();

  Seen(const Seen& from);
  Seen(Seen&& from) noexcept
    : Seen() {
    *this = ::std::move(from);
  }

  inline Seen& operator=(const Seen& from) {
    CopyFrom(from);
    return *this;
  }
  inline Seen& operator=(Seen&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Seen& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Seen* internal_default_instance() {
    return reinterpret_cast<const Seen*>(
               &_Seen_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Seen& a, Seen& b) {
    a.Swap(&b);
  }
  inline void Swap(Seen* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Seen* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Seen* New() const final {
    return CreateMaybeMessage<Seen>(nullptr);
  }

  Seen* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Seen>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Seen& from);
  void MergeFrom(const Seen& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Seen* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.Seen";
  }
  protected:
  explicit Seen(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_internal_5fmessage_2eproto);
    return ::descriptor_table_internal_5fmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampFieldNumber = 4,
    kUserIdFieldNumber = 1,
    kChannelIdFieldNumber = 2,
    kMessageIdFieldNumber = 3,
  };
  // .google.protobuf.Timestamp timestamp = 4;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // uint64 user_id = 1 [jstype = JS_STRING];
  void clear_user_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 user_id() const;
  void set_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_user_id() const;
  void _internal_set_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 channel_id = 2 [jstype = JS_STRING];
  void clear_channel_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 channel_id() const;
  void set_channel_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_channel_id() const;
  void _internal_set_channel_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 message_id = 3 [jstype = JS_STRING];
  void clear_message_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 message_id() const;
  void set_message_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_message_id() const;
  void _internal_set_message_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:msg.Seen)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint64 user_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 channel_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 message_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_internal_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class Status PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.Status) */ {
 public:
  inline Status() : Status(nullptr) {};
  virtual ~Status();

  Status(const Status& from);
  Status(Status&& from) noexcept
    : Status() {
    *this = ::std::move(from);
  }

  inline Status& operator=(const Status& from) {
    CopyFrom(from);
    return *this;
  }
  inline Status& operator=(Status&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Status& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Status* internal_default_instance() {
    return reinterpret_cast<const Status*>(
               &_Status_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Status& a, Status& b) {
    a.Swap(&b);
  }
  inline void Swap(Status* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Status* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Status* New() const final {
    return CreateMaybeMessage<Status>(nullptr);
  }

  Status* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Status>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Status& from);
  void MergeFrom(const Status& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Status* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.Status";
  }
  protected:
  explicit Status(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_internal_5fmessage_2eproto);
    return ::descriptor_table_internal_5fmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Status_Type Type;
  static constexpr Type UNKNOWN =
    Status_Type_UNKNOWN;
  static constexpr Type ONLINE =
    Status_Type_ONLINE;
  static constexpr Type OFFLINE =
    Status_Type_OFFLINE;
  static constexpr Type BUSY =
    Status_Type_BUSY;
  static constexpr Type NO_BOTHER =
    Status_Type_NO_BOTHER;
  static inline bool Type_IsValid(int value) {
    return Status_Type_IsValid(value);
  }
  static constexpr Type Type_MIN =
    Status_Type_Type_MIN;
  static constexpr Type Type_MAX =
    Status_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE =
    Status_Type_Type_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Type_descriptor() {
    return Status_Type_descriptor();
  }
  template<typename T>
  static inline const std::string& Type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Type_Name.");
    return Status_Type_Name(enum_t_value);
  }
  static inline bool Type_Parse(const std::string& name,
      Type* value) {
    return Status_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampFieldNumber = 3,
    kUserIdFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // .google.protobuf.Timestamp timestamp = 3;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // uint64 user_id = 1 [jstype = JS_STRING];
  void clear_user_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 user_id() const;
  void set_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_user_id() const;
  void _internal_set_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // .msg.Status.Type type = 2;
  void clear_type();
  ::msg::Status_Type type() const;
  void set_type(::msg::Status_Type value);
  private:
  ::msg::Status_Type _internal_type() const;
  void _internal_set_type(::msg::Status_Type value);
  public:

  // @@protoc_insertion_point(class_scope:msg.Status)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint64 user_id_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_internal_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class Typing PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.Typing) */ {
 public:
  inline Typing() : Typing(nullptr) {};
  virtual ~Typing();

  Typing(const Typing& from);
  Typing(Typing&& from) noexcept
    : Typing() {
    *this = ::std::move(from);
  }

  inline Typing& operator=(const Typing& from) {
    CopyFrom(from);
    return *this;
  }
  inline Typing& operator=(Typing&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Typing& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Typing* internal_default_instance() {
    return reinterpret_cast<const Typing*>(
               &_Typing_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Typing& a, Typing& b) {
    a.Swap(&b);
  }
  inline void Swap(Typing* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Typing* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Typing* New() const final {
    return CreateMaybeMessage<Typing>(nullptr);
  }

  Typing* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Typing>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Typing& from);
  void MergeFrom(const Typing& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Typing* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.Typing";
  }
  protected:
  explicit Typing(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_internal_5fmessage_2eproto);
    return ::descriptor_table_internal_5fmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampFieldNumber = 4,
    kUserIdFieldNumber = 1,
    kChannelIdFieldNumber = 2,
    kIsTypingFieldNumber = 3,
  };
  // .google.protobuf.Timestamp timestamp = 4;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // uint64 user_id = 1 [jstype = JS_STRING];
  void clear_user_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 user_id() const;
  void set_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_user_id() const;
  void _internal_set_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 channel_id = 2 [jstype = JS_STRING];
  void clear_channel_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 channel_id() const;
  void set_channel_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_channel_id() const;
  void _internal_set_channel_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // bool is_typing = 3;
  void clear_is_typing();
  bool is_typing() const;
  void set_is_typing(bool value);
  private:
  bool _internal_is_typing() const;
  void _internal_set_is_typing(bool value);
  public:

  // @@protoc_insertion_point(class_scope:msg.Typing)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint64 user_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 channel_id_;
  bool is_typing_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_internal_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class Notification PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.Notification) */ {
 public:
  inline Notification() : Notification(nullptr) {};
  virtual ~Notification();

  Notification(const Notification& from);
  Notification(Notification&& from) noexcept
    : Notification() {
    *this = ::std::move(from);
  }

  inline Notification& operator=(const Notification& from) {
    CopyFrom(from);
    return *this;
  }
  inline Notification& operator=(Notification&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Notification& default_instance();

  enum DataCase {
    kFriend = 1,
    kGroup = 2,
    kMoney = 3,
    kText = 4,
    DATA_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Notification* internal_default_instance() {
    return reinterpret_cast<const Notification*>(
               &_Notification_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Notification& a, Notification& b) {
    a.Swap(&b);
  }
  inline void Swap(Notification* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Notification* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Notification* New() const final {
    return CreateMaybeMessage<Notification>(nullptr);
  }

  Notification* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Notification>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Notification& from);
  void MergeFrom(const Notification& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Notification* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.Notification";
  }
  protected:
  explicit Notification(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_internal_5fmessage_2eproto);
    return ::descriptor_table_internal_5fmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFriendFieldNumber = 1,
    kGroupFieldNumber = 2,
    kMoneyFieldNumber = 3,
    kTextFieldNumber = 4,
  };
  // .msg.FriendNotification friend = 1;
  bool has_friend_() const;
  private:
  bool _internal_has_friend_() const;
  public:
  void clear_friend_();
  const ::msg::FriendNotification& friend_() const;
  ::msg::FriendNotification* release_friend_();
  ::msg::FriendNotification* mutable_friend_();
  void set_allocated_friend_(::msg::FriendNotification* friend_);
  private:
  const ::msg::FriendNotification& _internal_friend_() const;
  ::msg::FriendNotification* _internal_mutable_friend_();
  public:
  void unsafe_arena_set_allocated_friend_(
      ::msg::FriendNotification* friend_);
  ::msg::FriendNotification* unsafe_arena_release_friend_();

  // .msg.GroupNotification group = 2;
  bool has_group() const;
  private:
  bool _internal_has_group() const;
  public:
  void clear_group();
  const ::msg::GroupNotification& group() const;
  ::msg::GroupNotification* release_group();
  ::msg::GroupNotification* mutable_group();
  void set_allocated_group(::msg::GroupNotification* group);
  private:
  const ::msg::GroupNotification& _internal_group() const;
  ::msg::GroupNotification* _internal_mutable_group();
  public:
  void unsafe_arena_set_allocated_group(
      ::msg::GroupNotification* group);
  ::msg::GroupNotification* unsafe_arena_release_group();

  // .msg.MoneyNotification money = 3;
  bool has_money() const;
  private:
  bool _internal_has_money() const;
  public:
  void clear_money();
  const ::msg::MoneyNotification& money() const;
  ::msg::MoneyNotification* release_money();
  ::msg::MoneyNotification* mutable_money();
  void set_allocated_money(::msg::MoneyNotification* money);
  private:
  const ::msg::MoneyNotification& _internal_money() const;
  ::msg::MoneyNotification* _internal_mutable_money();
  public:
  void unsafe_arena_set_allocated_money(
      ::msg::MoneyNotification* money);
  ::msg::MoneyNotification* unsafe_arena_release_money();

  // .msg.TextNotification text = 4;
  bool has_text() const;
  private:
  bool _internal_has_text() const;
  public:
  void clear_text();
  const ::msg::TextNotification& text() const;
  ::msg::TextNotification* release_text();
  ::msg::TextNotification* mutable_text();
  void set_allocated_text(::msg::TextNotification* text);
  private:
  const ::msg::TextNotification& _internal_text() const;
  ::msg::TextNotification* _internal_mutable_text();
  public:
  void unsafe_arena_set_allocated_text(
      ::msg::TextNotification* text);
  ::msg::TextNotification* unsafe_arena_release_text();

  void clear_data();
  DataCase data_case() const;
  // @@protoc_insertion_point(class_scope:msg.Notification)
 private:
  class _Internal;
  void set_has_friend_();
  void set_has_group();
  void set_has_money();
  void set_has_text();

  inline bool has_data() const;
  inline void clear_has_data();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union DataUnion {
    DataUnion() {}
    ::msg::FriendNotification* friend__;
    ::msg::GroupNotification* group_;
    ::msg::MoneyNotification* money_;
    ::msg::TextNotification* text_;
  } data_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_internal_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class FriendNotification PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.FriendNotification) */ {
 public:
  inline FriendNotification() : FriendNotification(nullptr) {};
  virtual ~FriendNotification();

  FriendNotification(const FriendNotification& from);
  FriendNotification(FriendNotification&& from) noexcept
    : FriendNotification() {
    *this = ::std::move(from);
  }

  inline FriendNotification& operator=(const FriendNotification& from) {
    CopyFrom(from);
    return *this;
  }
  inline FriendNotification& operator=(FriendNotification&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FriendNotification& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FriendNotification* internal_default_instance() {
    return reinterpret_cast<const FriendNotification*>(
               &_FriendNotification_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(FriendNotification& a, FriendNotification& b) {
    a.Swap(&b);
  }
  inline void Swap(FriendNotification* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FriendNotification* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FriendNotification* New() const final {
    return CreateMaybeMessage<FriendNotification>(nullptr);
  }

  FriendNotification* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FriendNotification>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FriendNotification& from);
  void MergeFrom(const FriendNotification& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FriendNotification* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.FriendNotification";
  }
  protected:
  explicit FriendNotification(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_internal_5fmessage_2eproto);
    return ::descriptor_table_internal_5fmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef FriendNotification_Status Status;
  static constexpr Status UNKNOWN =
    FriendNotification_Status_UNKNOWN;
  static constexpr Status SENT =
    FriendNotification_Status_SENT;
  static constexpr Status ACCEPT =
    FriendNotification_Status_ACCEPT;
  static constexpr Status DECLINE =
    FriendNotification_Status_DECLINE;
  static constexpr Status BLOCK =
    FriendNotification_Status_BLOCK;
  static inline bool Status_IsValid(int value) {
    return FriendNotification_Status_IsValid(value);
  }
  static constexpr Status Status_MIN =
    FriendNotification_Status_Status_MIN;
  static constexpr Status Status_MAX =
    FriendNotification_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE =
    FriendNotification_Status_Status_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Status_descriptor() {
    return FriendNotification_Status_descriptor();
  }
  template<typename T>
  static inline const std::string& Status_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Status>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Status_Name.");
    return FriendNotification_Status_Name(enum_t_value);
  }
  static inline bool Status_Parse(const std::string& name,
      Status* value) {
    return FriendNotification_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kFromUserIdFieldNumber = 1,
    kToUserIdFieldNumber = 2,
    kStatusFieldNumber = 3,
  };
  // uint64 from_user_id = 1 [jstype = JS_STRING];
  void clear_from_user_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 from_user_id() const;
  void set_from_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_from_user_id() const;
  void _internal_set_from_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 to_user_id = 2 [jstype = JS_STRING];
  void clear_to_user_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 to_user_id() const;
  void set_to_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_to_user_id() const;
  void _internal_set_to_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // .msg.FriendNotification.Status status = 3;
  void clear_status();
  ::msg::FriendNotification_Status status() const;
  void set_status(::msg::FriendNotification_Status value);
  private:
  ::msg::FriendNotification_Status _internal_status() const;
  void _internal_set_status(::msg::FriendNotification_Status value);
  public:

  // @@protoc_insertion_point(class_scope:msg.FriendNotification)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint64 from_user_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 to_user_id_;
  int status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_internal_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class GroupNotification PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.GroupNotification) */ {
 public:
  inline GroupNotification() : GroupNotification(nullptr) {};
  virtual ~GroupNotification();

  GroupNotification(const GroupNotification& from);
  GroupNotification(GroupNotification&& from) noexcept
    : GroupNotification() {
    *this = ::std::move(from);
  }

  inline GroupNotification& operator=(const GroupNotification& from) {
    CopyFrom(from);
    return *this;
  }
  inline GroupNotification& operator=(GroupNotification&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GroupNotification& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GroupNotification* internal_default_instance() {
    return reinterpret_cast<const GroupNotification*>(
               &_GroupNotification_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(GroupNotification& a, GroupNotification& b) {
    a.Swap(&b);
  }
  inline void Swap(GroupNotification* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GroupNotification* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GroupNotification* New() const final {
    return CreateMaybeMessage<GroupNotification>(nullptr);
  }

  GroupNotification* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GroupNotification>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GroupNotification& from);
  void MergeFrom(const GroupNotification& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GroupNotification* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.GroupNotification";
  }
  protected:
  explicit GroupNotification(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_internal_5fmessage_2eproto);
    return ::descriptor_table_internal_5fmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:msg.GroupNotification)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_internal_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class MoneyNotification PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.MoneyNotification) */ {
 public:
  inline MoneyNotification() : MoneyNotification(nullptr) {};
  virtual ~MoneyNotification();

  MoneyNotification(const MoneyNotification& from);
  MoneyNotification(MoneyNotification&& from) noexcept
    : MoneyNotification() {
    *this = ::std::move(from);
  }

  inline MoneyNotification& operator=(const MoneyNotification& from) {
    CopyFrom(from);
    return *this;
  }
  inline MoneyNotification& operator=(MoneyNotification&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MoneyNotification& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MoneyNotification* internal_default_instance() {
    return reinterpret_cast<const MoneyNotification*>(
               &_MoneyNotification_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(MoneyNotification& a, MoneyNotification& b) {
    a.Swap(&b);
  }
  inline void Swap(MoneyNotification* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MoneyNotification* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MoneyNotification* New() const final {
    return CreateMaybeMessage<MoneyNotification>(nullptr);
  }

  MoneyNotification* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MoneyNotification>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MoneyNotification& from);
  void MergeFrom(const MoneyNotification& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MoneyNotification* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.MoneyNotification";
  }
  protected:
  explicit MoneyNotification(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_internal_5fmessage_2eproto);
    return ::descriptor_table_internal_5fmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTransactionFieldNumber = 1,
  };
  // .msg.History transaction = 1;
  bool has_transaction() const;
  private:
  bool _internal_has_transaction() const;
  public:
  void clear_transaction();
  const ::msg::History& transaction() const;
  ::msg::History* release_transaction();
  ::msg::History* mutable_transaction();
  void set_allocated_transaction(::msg::History* transaction);
  private:
  const ::msg::History& _internal_transaction() const;
  ::msg::History* _internal_mutable_transaction();
  public:
  void unsafe_arena_set_allocated_transaction(
      ::msg::History* transaction);
  ::msg::History* unsafe_arena_release_transaction();

  // @@protoc_insertion_point(class_scope:msg.MoneyNotification)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::msg::History* transaction_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_internal_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class TextNotification PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.TextNotification) */ {
 public:
  inline TextNotification() : TextNotification(nullptr) {};
  virtual ~TextNotification();

  TextNotification(const TextNotification& from);
  TextNotification(TextNotification&& from) noexcept
    : TextNotification() {
    *this = ::std::move(from);
  }

  inline TextNotification& operator=(const TextNotification& from) {
    CopyFrom(from);
    return *this;
  }
  inline TextNotification& operator=(TextNotification&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TextNotification& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TextNotification* internal_default_instance() {
    return reinterpret_cast<const TextNotification*>(
               &_TextNotification_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(TextNotification& a, TextNotification& b) {
    a.Swap(&b);
  }
  inline void Swap(TextNotification* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TextNotification* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TextNotification* New() const final {
    return CreateMaybeMessage<TextNotification>(nullptr);
  }

  TextNotification* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TextNotification>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TextNotification& from);
  void MergeFrom(const TextNotification& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TextNotification* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.TextNotification";
  }
  protected:
  explicit TextNotification(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_internal_5fmessage_2eproto);
    return ::descriptor_table_internal_5fmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:msg.TextNotification)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_internal_5fmessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Chat

// uint64 user_id = 1 [jstype = JS_STRING];
inline void Chat::clear_user_id() {
  user_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Chat::_internal_user_id() const {
  return user_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Chat::user_id() const {
  // @@protoc_insertion_point(field_get:msg.Chat.user_id)
  return _internal_user_id();
}
inline void Chat::_internal_set_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  user_id_ = value;
}
inline void Chat::set_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:msg.Chat.user_id)
}

// uint64 channel_id = 2 [jstype = JS_STRING];
inline void Chat::clear_channel_id() {
  channel_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Chat::_internal_channel_id() const {
  return channel_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Chat::channel_id() const {
  // @@protoc_insertion_point(field_get:msg.Chat.channel_id)
  return _internal_channel_id();
}
inline void Chat::_internal_set_channel_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  channel_id_ = value;
}
inline void Chat::set_channel_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_channel_id(value);
  // @@protoc_insertion_point(field_set:msg.Chat.channel_id)
}

// uint64 message_id = 3 [jstype = JS_STRING];
inline void Chat::clear_message_id() {
  message_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Chat::_internal_message_id() const {
  return message_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Chat::message_id() const {
  // @@protoc_insertion_point(field_get:msg.Chat.message_id)
  return _internal_message_id();
}
inline void Chat::_internal_set_message_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  message_id_ = value;
}
inline void Chat::set_message_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_message_id(value);
  // @@protoc_insertion_point(field_set:msg.Chat.message_id)
}

// .msg.ChatContent content = 4;
inline bool Chat::_internal_has_content() const {
  return this != internal_default_instance() && content_ != nullptr;
}
inline bool Chat::has_content() const {
  return _internal_has_content();
}
inline const ::msg::ChatContent& Chat::_internal_content() const {
  const ::msg::ChatContent* p = content_;
  return p != nullptr ? *p : *reinterpret_cast<const ::msg::ChatContent*>(
      &::msg::_ChatContent_default_instance_);
}
inline const ::msg::ChatContent& Chat::content() const {
  // @@protoc_insertion_point(field_get:msg.Chat.content)
  return _internal_content();
}
inline void Chat::unsafe_arena_set_allocated_content(
    ::msg::ChatContent* content) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(content_);
  }
  content_ = content;
  if (content) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg.Chat.content)
}
inline ::msg::ChatContent* Chat::release_content() {
  auto temp = unsafe_arena_release_content();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::msg::ChatContent* Chat::unsafe_arena_release_content() {
  // @@protoc_insertion_point(field_release:msg.Chat.content)
  
  ::msg::ChatContent* temp = content_;
  content_ = nullptr;
  return temp;
}
inline ::msg::ChatContent* Chat::_internal_mutable_content() {
  
  if (content_ == nullptr) {
    auto* p = CreateMaybeMessage<::msg::ChatContent>(GetArena());
    content_ = p;
  }
  return content_;
}
inline ::msg::ChatContent* Chat::mutable_content() {
  // @@protoc_insertion_point(field_mutable:msg.Chat.content)
  return _internal_mutable_content();
}
inline void Chat::set_allocated_content(::msg::ChatContent* content) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(content_);
  }
  if (content) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(content)->GetArena();
    if (message_arena != submessage_arena) {
      content = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, content, submessage_arena);
    }
    
  } else {
    
  }
  content_ = content;
  // @@protoc_insertion_point(field_set_allocated:msg.Chat.content)
}

// .google.protobuf.Timestamp timestamp = 5;
inline bool Chat::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool Chat::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Chat::_internal_timestamp() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Chat::timestamp() const {
  // @@protoc_insertion_point(field_get:msg.Chat.timestamp)
  return _internal_timestamp();
}
inline void Chat::unsafe_arena_set_allocated_timestamp(
    PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg.Chat.timestamp)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Chat::release_timestamp() {
  auto temp = unsafe_arena_release_timestamp();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Chat::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:msg.Chat.timestamp)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Chat::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    timestamp_ = p;
  }
  return timestamp_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Chat::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:msg.Chat.timestamp)
  return _internal_mutable_timestamp();
}
inline void Chat::set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:msg.Chat.timestamp)
}

// -------------------------------------------------------------------

// Seen

// uint64 user_id = 1 [jstype = JS_STRING];
inline void Seen::clear_user_id() {
  user_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Seen::_internal_user_id() const {
  return user_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Seen::user_id() const {
  // @@protoc_insertion_point(field_get:msg.Seen.user_id)
  return _internal_user_id();
}
inline void Seen::_internal_set_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  user_id_ = value;
}
inline void Seen::set_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:msg.Seen.user_id)
}

// uint64 channel_id = 2 [jstype = JS_STRING];
inline void Seen::clear_channel_id() {
  channel_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Seen::_internal_channel_id() const {
  return channel_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Seen::channel_id() const {
  // @@protoc_insertion_point(field_get:msg.Seen.channel_id)
  return _internal_channel_id();
}
inline void Seen::_internal_set_channel_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  channel_id_ = value;
}
inline void Seen::set_channel_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_channel_id(value);
  // @@protoc_insertion_point(field_set:msg.Seen.channel_id)
}

// uint64 message_id = 3 [jstype = JS_STRING];
inline void Seen::clear_message_id() {
  message_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Seen::_internal_message_id() const {
  return message_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Seen::message_id() const {
  // @@protoc_insertion_point(field_get:msg.Seen.message_id)
  return _internal_message_id();
}
inline void Seen::_internal_set_message_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  message_id_ = value;
}
inline void Seen::set_message_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_message_id(value);
  // @@protoc_insertion_point(field_set:msg.Seen.message_id)
}

// .google.protobuf.Timestamp timestamp = 4;
inline bool Seen::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool Seen::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Seen::_internal_timestamp() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Seen::timestamp() const {
  // @@protoc_insertion_point(field_get:msg.Seen.timestamp)
  return _internal_timestamp();
}
inline void Seen::unsafe_arena_set_allocated_timestamp(
    PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg.Seen.timestamp)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Seen::release_timestamp() {
  auto temp = unsafe_arena_release_timestamp();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Seen::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:msg.Seen.timestamp)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Seen::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    timestamp_ = p;
  }
  return timestamp_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Seen::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:msg.Seen.timestamp)
  return _internal_mutable_timestamp();
}
inline void Seen::set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:msg.Seen.timestamp)
}

// -------------------------------------------------------------------

// Status

// uint64 user_id = 1 [jstype = JS_STRING];
inline void Status::clear_user_id() {
  user_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Status::_internal_user_id() const {
  return user_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Status::user_id() const {
  // @@protoc_insertion_point(field_get:msg.Status.user_id)
  return _internal_user_id();
}
inline void Status::_internal_set_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  user_id_ = value;
}
inline void Status::set_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:msg.Status.user_id)
}

// .msg.Status.Type type = 2;
inline void Status::clear_type() {
  type_ = 0;
}
inline ::msg::Status_Type Status::_internal_type() const {
  return static_cast< ::msg::Status_Type >(type_);
}
inline ::msg::Status_Type Status::type() const {
  // @@protoc_insertion_point(field_get:msg.Status.type)
  return _internal_type();
}
inline void Status::_internal_set_type(::msg::Status_Type value) {
  
  type_ = value;
}
inline void Status::set_type(::msg::Status_Type value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:msg.Status.type)
}

// .google.protobuf.Timestamp timestamp = 3;
inline bool Status::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool Status::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Status::_internal_timestamp() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Status::timestamp() const {
  // @@protoc_insertion_point(field_get:msg.Status.timestamp)
  return _internal_timestamp();
}
inline void Status::unsafe_arena_set_allocated_timestamp(
    PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg.Status.timestamp)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Status::release_timestamp() {
  auto temp = unsafe_arena_release_timestamp();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Status::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:msg.Status.timestamp)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Status::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    timestamp_ = p;
  }
  return timestamp_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Status::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:msg.Status.timestamp)
  return _internal_mutable_timestamp();
}
inline void Status::set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:msg.Status.timestamp)
}

// -------------------------------------------------------------------

// Typing

// uint64 user_id = 1 [jstype = JS_STRING];
inline void Typing::clear_user_id() {
  user_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Typing::_internal_user_id() const {
  return user_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Typing::user_id() const {
  // @@protoc_insertion_point(field_get:msg.Typing.user_id)
  return _internal_user_id();
}
inline void Typing::_internal_set_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  user_id_ = value;
}
inline void Typing::set_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:msg.Typing.user_id)
}

// uint64 channel_id = 2 [jstype = JS_STRING];
inline void Typing::clear_channel_id() {
  channel_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Typing::_internal_channel_id() const {
  return channel_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Typing::channel_id() const {
  // @@protoc_insertion_point(field_get:msg.Typing.channel_id)
  return _internal_channel_id();
}
inline void Typing::_internal_set_channel_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  channel_id_ = value;
}
inline void Typing::set_channel_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_channel_id(value);
  // @@protoc_insertion_point(field_set:msg.Typing.channel_id)
}

// bool is_typing = 3;
inline void Typing::clear_is_typing() {
  is_typing_ = false;
}
inline bool Typing::_internal_is_typing() const {
  return is_typing_;
}
inline bool Typing::is_typing() const {
  // @@protoc_insertion_point(field_get:msg.Typing.is_typing)
  return _internal_is_typing();
}
inline void Typing::_internal_set_is_typing(bool value) {
  
  is_typing_ = value;
}
inline void Typing::set_is_typing(bool value) {
  _internal_set_is_typing(value);
  // @@protoc_insertion_point(field_set:msg.Typing.is_typing)
}

// .google.protobuf.Timestamp timestamp = 4;
inline bool Typing::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool Typing::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Typing::_internal_timestamp() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& Typing::timestamp() const {
  // @@protoc_insertion_point(field_get:msg.Typing.timestamp)
  return _internal_timestamp();
}
inline void Typing::unsafe_arena_set_allocated_timestamp(
    PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg.Typing.timestamp)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Typing::release_timestamp() {
  auto temp = unsafe_arena_release_timestamp();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Typing::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:msg.Typing.timestamp)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Typing::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    timestamp_ = p;
  }
  return timestamp_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* Typing::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:msg.Typing.timestamp)
  return _internal_mutable_timestamp();
}
inline void Typing::set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:msg.Typing.timestamp)
}

// -------------------------------------------------------------------

// Notification

// .msg.FriendNotification friend = 1;
inline bool Notification::_internal_has_friend_() const {
  return data_case() == kFriend;
}
inline bool Notification::has_friend_() const {
  return _internal_has_friend_();
}
inline void Notification::set_has_friend_() {
  _oneof_case_[0] = kFriend;
}
inline void Notification::clear_friend_() {
  if (_internal_has_friend_()) {
    if (GetArena() == nullptr) {
      delete data_.friend__;
    }
    clear_has_data();
  }
}
inline ::msg::FriendNotification* Notification::release_friend_() {
  // @@protoc_insertion_point(field_release:msg.Notification.friend)
  if (_internal_has_friend_()) {
    clear_has_data();
      ::msg::FriendNotification* temp = data_.friend__;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    data_.friend__ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::msg::FriendNotification& Notification::_internal_friend_() const {
  return _internal_has_friend_()
      ? *data_.friend__
      : *reinterpret_cast< ::msg::FriendNotification*>(&::msg::_FriendNotification_default_instance_);
}
inline const ::msg::FriendNotification& Notification::friend_() const {
  // @@protoc_insertion_point(field_get:msg.Notification.friend)
  return _internal_friend_();
}
inline ::msg::FriendNotification* Notification::unsafe_arena_release_friend_() {
  // @@protoc_insertion_point(field_unsafe_arena_release:msg.Notification.friend)
  if (_internal_has_friend_()) {
    clear_has_data();
    ::msg::FriendNotification* temp = data_.friend__;
    data_.friend__ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Notification::unsafe_arena_set_allocated_friend_(::msg::FriendNotification* friend_) {
  clear_data();
  if (friend_) {
    set_has_friend_();
    data_.friend__ = friend_;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg.Notification.friend)
}
inline ::msg::FriendNotification* Notification::_internal_mutable_friend_() {
  if (!_internal_has_friend_()) {
    clear_data();
    set_has_friend_();
    data_.friend__ = CreateMaybeMessage< ::msg::FriendNotification >(GetArena());
  }
  return data_.friend__;
}
inline ::msg::FriendNotification* Notification::mutable_friend_() {
  // @@protoc_insertion_point(field_mutable:msg.Notification.friend)
  return _internal_mutable_friend_();
}

// .msg.GroupNotification group = 2;
inline bool Notification::_internal_has_group() const {
  return data_case() == kGroup;
}
inline bool Notification::has_group() const {
  return _internal_has_group();
}
inline void Notification::set_has_group() {
  _oneof_case_[0] = kGroup;
}
inline void Notification::clear_group() {
  if (_internal_has_group()) {
    if (GetArena() == nullptr) {
      delete data_.group_;
    }
    clear_has_data();
  }
}
inline ::msg::GroupNotification* Notification::release_group() {
  // @@protoc_insertion_point(field_release:msg.Notification.group)
  if (_internal_has_group()) {
    clear_has_data();
      ::msg::GroupNotification* temp = data_.group_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    data_.group_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::msg::GroupNotification& Notification::_internal_group() const {
  return _internal_has_group()
      ? *data_.group_
      : *reinterpret_cast< ::msg::GroupNotification*>(&::msg::_GroupNotification_default_instance_);
}
inline const ::msg::GroupNotification& Notification::group() const {
  // @@protoc_insertion_point(field_get:msg.Notification.group)
  return _internal_group();
}
inline ::msg::GroupNotification* Notification::unsafe_arena_release_group() {
  // @@protoc_insertion_point(field_unsafe_arena_release:msg.Notification.group)
  if (_internal_has_group()) {
    clear_has_data();
    ::msg::GroupNotification* temp = data_.group_;
    data_.group_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Notification::unsafe_arena_set_allocated_group(::msg::GroupNotification* group) {
  clear_data();
  if (group) {
    set_has_group();
    data_.group_ = group;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg.Notification.group)
}
inline ::msg::GroupNotification* Notification::_internal_mutable_group() {
  if (!_internal_has_group()) {
    clear_data();
    set_has_group();
    data_.group_ = CreateMaybeMessage< ::msg::GroupNotification >(GetArena());
  }
  return data_.group_;
}
inline ::msg::GroupNotification* Notification::mutable_group() {
  // @@protoc_insertion_point(field_mutable:msg.Notification.group)
  return _internal_mutable_group();
}

// .msg.MoneyNotification money = 3;
inline bool Notification::_internal_has_money() const {
  return data_case() == kMoney;
}
inline bool Notification::has_money() const {
  return _internal_has_money();
}
inline void Notification::set_has_money() {
  _oneof_case_[0] = kMoney;
}
inline void Notification::clear_money() {
  if (_internal_has_money()) {
    if (GetArena() == nullptr) {
      delete data_.money_;
    }
    clear_has_data();
  }
}
inline ::msg::MoneyNotification* Notification::release_money() {
  // @@protoc_insertion_point(field_release:msg.Notification.money)
  if (_internal_has_money()) {
    clear_has_data();
      ::msg::MoneyNotification* temp = data_.money_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    data_.money_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::msg::MoneyNotification& Notification::_internal_money() const {
  return _internal_has_money()
      ? *data_.money_
      : *reinterpret_cast< ::msg::MoneyNotification*>(&::msg::_MoneyNotification_default_instance_);
}
inline const ::msg::MoneyNotification& Notification::money() const {
  // @@protoc_insertion_point(field_get:msg.Notification.money)
  return _internal_money();
}
inline ::msg::MoneyNotification* Notification::unsafe_arena_release_money() {
  // @@protoc_insertion_point(field_unsafe_arena_release:msg.Notification.money)
  if (_internal_has_money()) {
    clear_has_data();
    ::msg::MoneyNotification* temp = data_.money_;
    data_.money_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Notification::unsafe_arena_set_allocated_money(::msg::MoneyNotification* money) {
  clear_data();
  if (money) {
    set_has_money();
    data_.money_ = money;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg.Notification.money)
}
inline ::msg::MoneyNotification* Notification::_internal_mutable_money() {
  if (!_internal_has_money()) {
    clear_data();
    set_has_money();
    data_.money_ = CreateMaybeMessage< ::msg::MoneyNotification >(GetArena());
  }
  return data_.money_;
}
inline ::msg::MoneyNotification* Notification::mutable_money() {
  // @@protoc_insertion_point(field_mutable:msg.Notification.money)
  return _internal_mutable_money();
}

// .msg.TextNotification text = 4;
inline bool Notification::_internal_has_text() const {
  return data_case() == kText;
}
inline bool Notification::has_text() const {
  return _internal_has_text();
}
inline void Notification::set_has_text() {
  _oneof_case_[0] = kText;
}
inline void Notification::clear_text() {
  if (_internal_has_text()) {
    if (GetArena() == nullptr) {
      delete data_.text_;
    }
    clear_has_data();
  }
}
inline ::msg::TextNotification* Notification::release_text() {
  // @@protoc_insertion_point(field_release:msg.Notification.text)
  if (_internal_has_text()) {
    clear_has_data();
      ::msg::TextNotification* temp = data_.text_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    data_.text_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::msg::TextNotification& Notification::_internal_text() const {
  return _internal_has_text()
      ? *data_.text_
      : *reinterpret_cast< ::msg::TextNotification*>(&::msg::_TextNotification_default_instance_);
}
inline const ::msg::TextNotification& Notification::text() const {
  // @@protoc_insertion_point(field_get:msg.Notification.text)
  return _internal_text();
}
inline ::msg::TextNotification* Notification::unsafe_arena_release_text() {
  // @@protoc_insertion_point(field_unsafe_arena_release:msg.Notification.text)
  if (_internal_has_text()) {
    clear_has_data();
    ::msg::TextNotification* temp = data_.text_;
    data_.text_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Notification::unsafe_arena_set_allocated_text(::msg::TextNotification* text) {
  clear_data();
  if (text) {
    set_has_text();
    data_.text_ = text;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg.Notification.text)
}
inline ::msg::TextNotification* Notification::_internal_mutable_text() {
  if (!_internal_has_text()) {
    clear_data();
    set_has_text();
    data_.text_ = CreateMaybeMessage< ::msg::TextNotification >(GetArena());
  }
  return data_.text_;
}
inline ::msg::TextNotification* Notification::mutable_text() {
  // @@protoc_insertion_point(field_mutable:msg.Notification.text)
  return _internal_mutable_text();
}

inline bool Notification::has_data() const {
  return data_case() != DATA_NOT_SET;
}
inline void Notification::clear_has_data() {
  _oneof_case_[0] = DATA_NOT_SET;
}
inline Notification::DataCase Notification::data_case() const {
  return Notification::DataCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// FriendNotification

// uint64 from_user_id = 1 [jstype = JS_STRING];
inline void FriendNotification::clear_from_user_id() {
  from_user_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 FriendNotification::_internal_from_user_id() const {
  return from_user_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 FriendNotification::from_user_id() const {
  // @@protoc_insertion_point(field_get:msg.FriendNotification.from_user_id)
  return _internal_from_user_id();
}
inline void FriendNotification::_internal_set_from_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  from_user_id_ = value;
}
inline void FriendNotification::set_from_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_from_user_id(value);
  // @@protoc_insertion_point(field_set:msg.FriendNotification.from_user_id)
}

// uint64 to_user_id = 2 [jstype = JS_STRING];
inline void FriendNotification::clear_to_user_id() {
  to_user_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 FriendNotification::_internal_to_user_id() const {
  return to_user_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 FriendNotification::to_user_id() const {
  // @@protoc_insertion_point(field_get:msg.FriendNotification.to_user_id)
  return _internal_to_user_id();
}
inline void FriendNotification::_internal_set_to_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  to_user_id_ = value;
}
inline void FriendNotification::set_to_user_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_to_user_id(value);
  // @@protoc_insertion_point(field_set:msg.FriendNotification.to_user_id)
}

// .msg.FriendNotification.Status status = 3;
inline void FriendNotification::clear_status() {
  status_ = 0;
}
inline ::msg::FriendNotification_Status FriendNotification::_internal_status() const {
  return static_cast< ::msg::FriendNotification_Status >(status_);
}
inline ::msg::FriendNotification_Status FriendNotification::status() const {
  // @@protoc_insertion_point(field_get:msg.FriendNotification.status)
  return _internal_status();
}
inline void FriendNotification::_internal_set_status(::msg::FriendNotification_Status value) {
  
  status_ = value;
}
inline void FriendNotification::set_status(::msg::FriendNotification_Status value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:msg.FriendNotification.status)
}

// -------------------------------------------------------------------

// GroupNotification

// -------------------------------------------------------------------

// MoneyNotification

// .msg.History transaction = 1;
inline bool MoneyNotification::_internal_has_transaction() const {
  return this != internal_default_instance() && transaction_ != nullptr;
}
inline bool MoneyNotification::has_transaction() const {
  return _internal_has_transaction();
}
inline const ::msg::History& MoneyNotification::_internal_transaction() const {
  const ::msg::History* p = transaction_;
  return p != nullptr ? *p : *reinterpret_cast<const ::msg::History*>(
      &::msg::_History_default_instance_);
}
inline const ::msg::History& MoneyNotification::transaction() const {
  // @@protoc_insertion_point(field_get:msg.MoneyNotification.transaction)
  return _internal_transaction();
}
inline void MoneyNotification::unsafe_arena_set_allocated_transaction(
    ::msg::History* transaction) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(transaction_);
  }
  transaction_ = transaction;
  if (transaction) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg.MoneyNotification.transaction)
}
inline ::msg::History* MoneyNotification::release_transaction() {
  auto temp = unsafe_arena_release_transaction();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::msg::History* MoneyNotification::unsafe_arena_release_transaction() {
  // @@protoc_insertion_point(field_release:msg.MoneyNotification.transaction)
  
  ::msg::History* temp = transaction_;
  transaction_ = nullptr;
  return temp;
}
inline ::msg::History* MoneyNotification::_internal_mutable_transaction() {
  
  if (transaction_ == nullptr) {
    auto* p = CreateMaybeMessage<::msg::History>(GetArena());
    transaction_ = p;
  }
  return transaction_;
}
inline ::msg::History* MoneyNotification::mutable_transaction() {
  // @@protoc_insertion_point(field_mutable:msg.MoneyNotification.transaction)
  return _internal_mutable_transaction();
}
inline void MoneyNotification::set_allocated_transaction(::msg::History* transaction) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(transaction_);
  }
  if (transaction) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(transaction)->GetArena();
    if (message_arena != submessage_arena) {
      transaction = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, transaction, submessage_arena);
    }
    
  } else {
    
  }
  transaction_ = transaction;
  // @@protoc_insertion_point(field_set_allocated:msg.MoneyNotification.transaction)
}

// -------------------------------------------------------------------

// TextNotification

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace msg

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::msg::Status_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::msg::Status_Type>() {
  return ::msg::Status_Type_descriptor();
}
template <> struct is_proto_enum< ::msg::FriendNotification_Status> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::msg::FriendNotification_Status>() {
  return ::msg::FriendNotification_Status_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_internal_5fmessage_2eproto
